EntityTypes:
  - Entity

Predicates:
  - IsPedestrian:
      arity: 1
      method: IsPed(Entity)
      function: logicity.utils.pred_converter.z3_local.IsPed
      description: Checks if entity x is a pedestrian.
  - IsCar:
      arity: 1
      method: IsCar(Entity)
      function: logicity.utils.pred_converter.z3_local.IsCar
      description: Checks if agent x is a car.
  - IsAmbulance:
      arity: 1
      method: IsAmb(Entity)
      function: logicity.utils.pred_converter.z3_local.IsAmb
      description: Checks if the agent has concept "ambulance".
  - IsBus:
      arity: 1
      method: IsBus(Entity)
      function: logicity.utils.pred_converter.z3_local.IsBus
      description: Checks if the agent has concept "bus".
  - IsPolice:
      arity: 1
      method: IsPolice(Entity)
      function: logicity.utils.pred_converter.z3_local.IsPolice
      description: Checks if the agent has concept "police".
  - IsTiro:
      arity: 1
      method: IsTiro(Entity)
      function: logicity.utils.pred_converter.z3_local.IsTiro
      description: Checks if the agent has concept "tiro".
  - IsReckless:
      arity: 1
      method: IsTiro(Entity)
      function: logicity.utils.pred_converter.z3_local.IsReckless
      description: Checks if the agent has concept "reckless".
  - IsOld:
      arity: 1
      method: IsOld(Entity)
      function: logicity.utils.pred_converter.z3_local.IsOld
      description: Checks if the agent has concept "old".
  - IsYoung:
      arity: 1
      method: IsYoung(Entity)
      function: logicity.utils.pred_converter.z3_local.IsYoung
      description: Checks if the agent has concept "young".
  - IsInInter:
      arity: 1
      method: IsInInter(Entity)
      function: logicity.utils.pred_converter.z3_local.IsInInter
      description: Checks if agent x is in intersection.
  - IsClose:
      arity: 2
      method: IsClose(Agent, Agent)
      function: logicity.utils.pred_converter.z3_local.IsClose
      description: Checks if agent x close to agent y.
  - HigherPri:
      arity: 2
      method: HigherPri(Agent, Agent)
      function: logicity.utils.pred_converter.z3_local.HigherPri
      description: Checks if agent x, x has higher priority to y.
  - CollidingClose:
      arity: 2
      method: CollidingClose(Agent, Agent)
      function: logicity.utils.pred_converter.z3_local.CollidingClose
      description: Checks if agent x is about to collide with agent y.
  - LeftOf:
      arity: 2
      method: LeftOf(Agent, Agent)
      function: logicity.utils.pred_converter.z3_local.LeftOf
      description: Checks if agent x is left of agent y.
  - RightOf:
      arity: 2
      method: RightOf(Agent, Agent)
      function: logicity.utils.pred_converter.z3_local.RightOf
      description: Checks if agent x is right of agent y.
  - Stop:
      arity: 1
      method: Stop(Agent)
      function: None
      description: Stop action.
  - Fast:
      arity: 1
      method: Fast(Agent)
      function: None
      description: Fast action.
  - Normal:
      arity: 1
      method: Normal(Agent)
      function: None
      description: Normal action.
  - Slow:
      arity: 1
      method: Slow(Agent)
      function: None
      description: Slow action.