# predicates_rules.yml

predicates:
  - IsAtIntersection: 
      arity: 1
      method: utils.lnn.check_is_at_intersection
      description: Checks if the agent is at an intersection.
  - ArrivedFirst: 
      arity: 1
      method: utils.lnn.arrived_first
      description: Checks if this vehicle arrived at the intersection before all others.
    # all the actions will not have methods, as they are not executed by the simulator, they are initalized as false (0, 0)
  - Stop:
      arity: 1
      method: None
      description: stop action.

rules:
  - STOP: 
      formula: Implies(And(IsAtIntersection(x), Not(ArrivedFirst(x))), Stop(x))
      description: If an agent x IsAtIntersection and not ArrivedFirst, it stops.
  - NotSTOP: 
      formula: Implies(Or(Not(IsAtIntersection(x)), ArrivedFirst(x)), Not(Stop(x)))
      description: Otherwise, do not stop.

