predicates:
  - IsAtIntersection:
      arity: 1
      method: utils.lnn_pred_converter.check_is_at_intersection
      description: Checks if the agent is at an intersection.
  - IsCar:
      arity: 1
      method: utils.lnn_pred_converter.is_car
      description: Checks if the agent is a car.
  - IsPedestrian:
      arity: 1
      method: utils.lnn_pred_converter.is_pedestrian
      description: Checks if the agent is a pedestrian.
  - IntersectionEmpty:
      arity: 1
      method: utils.lnn_pred_converter.intersection_empty
      description: Checks if the intersection is not empty.
  - Stop:
      arity: 1
      method: None
      description: Stop action.

rules:
  - CAR_MOVE_1:
      formula: Implies(IsCar(x), Not(Stop(x)))
      description: Cars move if they are not at intersections.
  - PEDESTRIAN_MOVE_1:
      formula: Implies(And(IsPedestrian(x), Not(IsAtIntersection(x))), Not(Stop(x)))
      description: Pedestrians move if they are not at intersections.
  - PEDESTRIAN_MOVE_2:
      formula: Implies(And(IsPedestrian(x), IsAtIntersection(x), IntersectionEmpty(x)), Not(Stop(x)))
      description: Pedestrians move if they are at intersections and the intersection is empty.
  - PEDESTRIAN_STOP:
      formula: Implies(And(IsPedestrian(x), IsAtIntersection(x), Not(IntersectionEmpty(x))), Stop(x))
      description: Otherwise, pedestrians stop.
