model_type: "SATNet"
model_path: null
train_data_path: 'dataset/logic/easy_42_11.17/train.pkl'
test_data_path: 'dataset/logic/easy_42_11.17/test.pkl'
log_dir: 'log/logic'
exp: 'easy_satnet_clean'
batch_size: 256
epochs: 40
save_freq: 5
m: 20
aux: 12
prox_lam: 1e-1
uni_boundary: 0.0
w_bernoulli: False
irr_c: 0
learning_rate: 0.0001