model_type: "Symbolic_Decision_Tree"
train_data_path: 'dataset/logic/easy_42_11.17/train.pkl'
test_data_path: 'dataset/logic/easy_42_11.17/test.pkl'
log_dir: 'log/logic'
exp: 'easy_dt_rule_0.5'
uni_boundary: 0.2
w_bernoulli: True
irr_c: 0