Rules:
  - Stop:
      formula: |
        Stop(entity) == Exists(
          [dummyEntity], 
          Or(
            And(
              IsAtInter(entity), 
              IsInInter(dummyEntity), 
            ),
            And(
              IsAtInter(entity), 
              IsAtInter(dummyEntity), 
              HigherPri(dummyEntity, entity),
            ),
            CollidingClose(entity, dummyEntity)
          )
        )
      description: Or version of the 3 stop rule.
