Rules:
  - Stop:
      formula: |
        Stop(entity) == Exists(
          [dummyEntity], 
          Or(
            And(
              IsInInter(entity), 
              IsInInter(dummyEntity), 
              HigherPri(dummyEntity, entity),
            ),
            CollidingClose(entity, dummyEntity)
          )
        )
      description: Or version of the following 3 stop rule.
