Rules:
  - Stop:
      formula: |
        Stop(entity) == Exists(
          [dummyEntity], 
          Or(
            And(
              IsAtInter(entity), 
              IsInInter(dummyEntity), 
            ),
            And(
              IsAtInter(entity), 
              IsAtInter(dummyEntity), 
              HigherPri(dummyEntity, entity),
            ),
            CollidingClose(entity, dummyEntity)
          )
        )
      description: Or version of the 3 stop rule.
  - Slow:
      formula: |
        Not(Slow(entity))
      description: Hard constrain, no slow allowed.
  - Fast:
      formula: |
        Not(Fast(entity))
      description: Hard constrain, no Fast allowed.
