# General simulation settings
simulation:
  map_yaml_file: "config/maps/v1.1.yaml"       # OpenAI Gym environment name
  agent_yaml_file: "config/agents/debug.yaml" # Agents in the simulation
  rule_type: "Z3_Local"               # Maximum steps in each episode
  rule_yaml_file: "config/rules/Z3/easy/easy_rule_local.yaml"                 # Whether to render the environment
  rl: true
  debug: false
  rl_agent: 
    agent_name: "Pedestrian_1"               # ID of the RL agent, this is the agent id in the agent yaml file
    horizon: 500                          # Maximum steps in each episode 

eval_checkpoint:
  eval_freq: 20000                        # This is the frequency of evaluation, will be multiplied by num_envs
  save_freq: 20000
  save_path: './checkpoints/'
  name_prefix: 'res18_model_1e-5'

# Stable Baselines specific settings
stable_baselines:
  algorithm: "PPO"
  policy_kwargs:
    features_extractor_module: "logicity.rl_agent.policy.neural" # Module path
    features_extractor_class: "NeuralNav"
    features_extractor_kwargs:
      features_dim: 64
  hyperparameters:
    learning_rate: 0.00001          # Learning rate
    gamma: 0.99                   # Discount factor
    n_steps: 2048                 # Number of steps to run for each environment per update
    ent_coef: 0.0                 # Entropy coefficient
    verbose: 1                    # Verbosity level
    tensorboard_log: "./tb_logs"  # Tensorboard log directory
  train: false                   # Whether to train the model
  checkpoint_path: "checkpoints/res18_model_rw2/best_model.zip"           # Path to a checkpoint to restore the model from
  num_envs: 2                   # Number of environments to run in parallel
  total_timesteps: 5000000    # Total number of timesteps to run for all environments combined
