entity:
  - Agents
  - Intersections

predicates:
  - IsAt:
      arity: 2
      method: utils.pred_converter.is_at
      description: Checks if x is at y.
  - IsIntersection:
      arity: 1
      method: utils.pred_converter.is_intersection
      description: Checks if x is an intersection.
  - IsPedestrian:
      arity: 1
      method: utils.pred_converter.is_pedestrian
      description: Checks if the agent is a pedestrian.
  - IsInterCarEmpty:
      arity: 1
      method: utils.pred_converter.is_inter_carempty
      description: Checks if the intersection x is not empty with cars.
  - Stop:
      arity: 1
      method: None
      description: Stop action.
#   - Normal:
#       arity: 1
#       description: Normal is default action, it will be false if any other actions are true.

rules:
  - Pedestrian_Stop:
      formula: Forall(x, Implies(Exists(y, And(IsPedestrian(x), IsIntersection(y), IsAt(x, y), Not(IsInterCarEmpty(y)))), Stop(x)))
      description: pedestrians at intersection, not intersection empty with cars, stop