EntityTypes:
  - Agent
  - Intersection

Predicates:
  - IsAt:
      type: D
      arity: 2
      method: IsAt(Agent, Intersection)
      function: utils.pred_converter.z3.IsAt
      description: Checks if agent x is at intersection y.
  - IsPedestrian:
      type: S
      arity: 1
      method: IsPed(Agent)
      function: utils.pred_converter.z3.IsPed
      description: Checks if agent x is a pedestrian.
  - IsCar:
      type: S
      arity: 1
      method: IsCar(Agent)
      function: utils.pred_converter.z3.IsCar
      description: Checks if agent x is a car.
  - IsInterEmpty:
      type: D
      arity: 1
      method: IsInterEmpty(Intersection)
      function: utils.pred_converter.z3.IsInterEmpty
      description: Checks if the intersection x is empty.
  - IsInterCarEmpty:
      type: D
      arity: 1
      method: IsInterCarEmpty(Intersection)
      function: utils.pred_converter.z3.IsInterCarEmpty
      description: Checks if the intersection x is empty with cars.
  - HigherPri:
      type: D
      arity: 2
      method: HigherPri(Agent, Agent)
      function: utils.pred_converter.z3.HigherPri
      description: Checks if agent x, x has higher priority to y.
  - Stop:
      type: S
      arity: 1
      method: Stop(Agent)
      function: None
      description: Stop action.

Rules:
  - Stop:
      formula: Stop(agent) == Exists([dummyIntersection, dummyAgent], Or(And(IsCar(agent), IsAt(agent, dummyIntersection), IsAt(dummyAgent, dummyIntersection), IsInterEmpty(dummyIntersection), Or(HigherPri(dummyAgent, agent), IsPedestrian(dummyAgent))), And(IsPedestrian(agent), IsAt(agent, dummyIntersection), Not(IsInterCarEmpty(dummyIntersection))), And(IsCar(agent), IsAt(agent, dummyIntersection), Not(And(IsInterEmpty(dummyIntersection), IsInterCarEmpty(dummyIntersection))))))
      description: Or version of the following 3 stop rule.
#   - Cars_Stop1:
#       formula: And(IsCar(agent), IsAt(agent, dummyIntersection), Not(IsInterEmpty(dummyIntersection)))) == Stop(agent)
#       description: cars at intersection, not intersection empty, stop
#   - Cars_Stop2:
#       formula: And(IsCar(agent), IsAt(agent, dummyIntersection), IsAt(dummyAgent, dummyIntersection), IsInterEmpty(dummyIntersection), Or(HigherPri(dummyAgent, agent), IsPedestrian(dummyAgent))) == Stop(agent)
#       description: cars at intersection, intersection empty, higher priority car or ped is at intersection, stop
#   - Pedestrians_Stop1:
#       formula: And(IsPedestrian(agent), IsAt(agent, dummyIntersection), Not(IsInterCarEmpty(dummyIntersection)))) == Stop(agent)
#       description: pedestrians at intersection, not intersection empty with cars, stop
