Rules:
  - Stop:
      formula: |
        Stop(entity) == Exists(
          [dummyEntityA], 
          Or(
            And(
              Not(IsAmbulance(entity)), 
              IsAtInter(entity), 
              IsInInter(dummyEntityA), 
            ),
            And(
              Not(IsAmbulance(entity)), 
              IsAtInter(entity), 
              IsAtInter(dummyEntityA), 
              HigherPri(dummyEntityA, entity),
            ),
            And(
              Not(IsAmbulance(entity)), 
              IsInInter(entity), 
              IsInInter(dummyEntityA), 
              IsAmbulance(dummyEntityA)
            ),
            And(
              Not(IsAmbulance(entity)), 
              Not(IsPolice(entity)), 
              IsCar(entity),
              LeftOf(dummyEntityA, entity), 
              IsPolice(dummyEntityA)
            ),
            And(
              IsBus(entity),
              RightOf(dummyEntityA, entity), 
              IsPedestrian(dummyEntityA)
            ),
            And(
              IsAmbulance(entity), 
              RightOf(entity, dummyEntityA), 
              IsOld(dummyEntityA)
            ),
            CollidingClose(entity, dummyEntityA)
          )
        )
      description: Medium stop rule.
  - Slow:
      formula: |
        Slow(entity) == Exists(
          [dummyEntityA, dummyEntityB], 
          Or(
            And(
              Not(Stop(entity)), 
              IsTiro(entity), 
              IsPedestrian(dummyEntityA), 
              IsClose(entity, dummyEntityA)
            ),
            And(
              Not(Stop(entity)), 
              Not(IsReckless(entity)),
              IsCar(entity), 
              IsInInter(entity),
              IsAtInter(dummyEntityA)
            ),
            And(
              Not(Stop(entity)), 
              IsPolice(entity),
              IsYoung(dummyEntityA),
              IsYoung(dummyEntityB),
              NextTo(dummyEntityA, dummyEntityB)
            )
          )
        )
      description: Combined Or version of the Slow rules for vehicles.
  - Fast:
      formula: |
        Fast(entity) == Exists(
          [dummyEntityA], 
          Or(
            And(
              Not(Stop(entity)), 
              IsReckless(entity), 
              IsAtInter(dummyEntityA), 
            ),
            And(
              Not(Stop(entity)), 
              IsBus(entity),
            ),
            And(
              Not(Stop(entity)), 
              IsPolice(entity),
              IsReckless(dummyEntityA)
            )
          )
        )
      description: Combined Or version of the Fast rules for vehicles.