Rules:
  - Stop:
      formula: |
        Stop(entity) == Exists(
          [dummyEntity], 
          Or(
            And(
              Not(IsAmbulance(entity)), 
              IsAtInter(entity), 
              IsInInter(dummyEntity), 
            ),
            And(
              Not(IsAmbulance(entity)), 
              IsAtInter(entity), 
              IsAtInter(dummyEntity), 
              HigherPri(dummyEntity, entity),
            ),
            And(
              Not(IsOld(entity)),
              IsPedestrian(entity), 
              IsOld(dummyEntity), 
              IsClose(entity, dummyEntity)
            ),
            And(
              Not(IsAmbulance(entity)), 
              IsInInter(entity), 
              IsInInter(dummyEntity), 
              IsAmbulance(dummyEntity)
            ),
            And(
              Not(IsAmbulance(agent)),
              CollidingClose(agent, dummyAgent)
            )
          )
        )
      description: Medium stop rule.
  - Fast:
      formula: Fast(agent) == Exists(
          [dummyEntity], 
          Or(
            And(
              Not(Stop(entity)), 
              Not(IsInInter(entity)),
              IsAmbulance(entity), 
            ),
            And(
              Not(Stop(entity)), 
              IsReckless(entity), 
              IsPedestrian(dummyEntity), 
              IsClose(entity, dummyEntity)
            ),
          )
        )
      description: If not stop, ambulances moves fast, reckless driver drives fast when close to pedestrian.
  - Slow:
      formula: |
        Slow(agent) == Exists(
          [dummyEntity], 
          Or(
            And(
              Not(Stop(entity)), 
              IsTiro(entity), 
              IsOld(dummyEntity), 
              IsClose(entity, dummyEntity)
            ),
            And(
              Not(Stop(entity)), 
              IsCar(entity), 
              IsInInter(entity, dummyEntity)
            )
          )
        )
      description: Combined Or version of the Slow rules for vehicles.
