Rules:
  Sim: # how the determinist agents move
    - name: Stop
      formula: |
        Stop(entity) == Exists(
          [dummyEntityA, dummyEntityB], 
          Or(
            And(
              Not(IsAmbulance(entity)), 
              Not(IsOld(entity)),
              IsAtInter(entity), 
              IsInInter(dummyEntityA), 
            ),
            And(
              Not(IsAmbulance(entity)), 
              Not(IsOld(entity)),
              IsAtInter(entity), 
              IsAtInter(dummyEntityA), 
              HigherPri(dummyEntityA, entity),
            ),
            And(
              Not(IsAmbulance(entity)), 
              Not(IsOld(entity)),
              IsInInter(entity), 
              IsInInter(dummyEntityA), 
              IsAmbulance(dummyEntityA)
            ),
            And(
              Not(IsAmbulance(entity)), 
              Not(IsPolice(entity)), 
              IsCar(entity),
              Not(IsInInter(entity)),
              Not(IsAtInter(entity)),
              LeftOf(dummyEntityA, entity), 
              IsClose(dummyEntityA, entity),
              IsPolice(dummyEntityA)
            ),
            And(
              IsBus(entity),
              Not(IsInInter(entity)),
              Not(IsAtInter(entity)),
              RightOf(dummyEntityA, entity), 
              NextTo(dummyEntityA, entity),
              IsPedestrian(dummyEntityA)
            ),
            And(
              IsAmbulance(entity), 
              RightOf(dummyEntityA, entity), 
              IsOld(dummyEntityA)
            ),
            And(
              Not(IsAmbulance(entity)), 
              Not(IsOld(entity)),
              CollidingClose(entity, dummyEntityA)
            )
          )
        )
      description: Medium stop rule.
  Task: # how the reward/score is calculated
    - name: Medium Stop
      description: should not collide.
      dead: true
      reward: -30
      formula: |
        Implies(Exists(
          [dummyEntityA, dummyEntityB], 
            Or(
              And(
                Not(IsAmbulance(entity)), 
                Not(IsOld(entity)),
                IsAtInter(entity), 
                IsInInter(dummyEntityA), 
              ),
              And(
                Not(IsAmbulance(entity)), 
                Not(IsOld(entity)),
                IsAtInter(entity), 
                IsAtInter(dummyEntityA), 
                HigherPri(dummyEntityA, entity),
              ),
              And(
                Not(IsAmbulance(entity)), 
                Not(IsOld(entity)),
                IsInInter(entity), 
                IsInInter(dummyEntityA), 
                IsAmbulance(dummyEntityA)
              ),
              And(
                Not(IsAmbulance(entity)), 
                Not(IsPolice(entity)), 
                IsCar(entity),
                Not(IsInInter(entity)),
                Not(IsAtInter(entity)),
                LeftOf(dummyEntityA, entity), 
                IsClose(dummyEntityA, entity),
                IsPolice(dummyEntityA)
              ),
              And(
                IsBus(entity),
                Not(IsInInter(entity)),
                Not(IsAtInter(entity)),
                RightOf(dummyEntityA, entity), 
                NextTo(dummyEntityA, entity),
                IsPedestrian(dummyEntityA)
              ),
              And(
                IsAmbulance(entity), 
                RightOf(dummyEntityA, entity), 
                IsOld(dummyEntityA)
              ),
              And(
                Not(IsAmbulance(entity)), 
                Not(IsOld(entity)),
                CollidingClose(entity, dummyEntityA)
              )
            )
          ),
          Stop(entity)
        )