buildings:
- block: 1
  height: 24
  position:
  - 16
  - 16
  size:
  - 10
  - 10
  type: Office
- block: 1
  height: 16
  position:
  - 16
  - 31
  size:
  - 10
  - 10
  type: Store
- block: 1
  height: 20
  position:
  - 31
  - 16
  size:
  - 10
  - 10
  type: Gas Station
- block: 1
  height: 13
  position:
  - 31
  - 31
  size:
  - 10
  - 10
  type: Garage
- block: 2
  height: 12
  position:
  - 16
  - 62
  size:
  - 10
  - 10
  type: House
- block: 2
  height: 11
  position:
  - 16
  - 77
  size:
  - 10
  - 10
  type: House
- block: 2
  height: 15
  position:
  - 31
  - 62
  size:
  - 10
  - 10
  type: Store
- block: 2
  height: 10
  position:
  - 31
  - 77
  size:
  - 10
  - 10
  type: House
- block: 3
  height: 21
  position:
  - 16
  - 108
  size:
  - 10
  - 10
  type: Office
- block: 3
  height: 19
  position:
  - 16
  - 123
  size:
  - 10
  - 10
  type: House
- block: 3
  height: 25
  position:
  - 31
  - 108
  size:
  - 10
  - 10
  type: House
- block: 3
  height: 24
  position:
  - 31
  - 123
  size:
  - 10
  - 10
  type: Office
- block: 4
  height: 21
  position:
  - 16
  - 154
  size:
  - 10
  - 10
  type: Store
- block: 4
  height: 12
  position:
  - 16
  - 169
  size:
  - 10
  - 10
  type: Garage
- block: 4
  height: 16
  position:
  - 31
  - 154
  size:
  - 10
  - 10
  type: Store
- block: 4
  height: 16
  position:
  - 31
  - 169
  size:
  - 10
  - 10
  type: House
- block: 5
  height: 23
  position:
  - 16
  - 200
  size:
  - 10
  - 10
  type: House
- block: 5
  height: 18
  position:
  - 16
  - 215
  size:
  - 10
  - 10
  type: Store
- block: 5
  height: 11
  position:
  - 31
  - 200
  size:
  - 10
  - 10
  type: House
- block: 5
  height: 24
  position:
  - 31
  - 215
  size:
  - 10
  - 10
  type: Store
- block: 6
  height: 21
  position:
  - 62
  - 16
  size:
  - 10
  - 10
  type: Store
- block: 6
  height: 24
  position:
  - 62
  - 31
  size:
  - 10
  - 10
  type: Garage
- block: 6
  height: 26
  position:
  - 77
  - 16
  size:
  - 10
  - 10
  type: House
- block: 6
  height: 17
  position:
  - 77
  - 31
  size:
  - 10
  - 10
  type: Office
- block: 7
  height: 15
  position:
  - 62
  - 62
  size:
  - 10
  - 10
  type: Store
- block: 7
  height: 13
  position:
  - 62
  - 77
  size:
  - 10
  - 10
  type: Office
- block: 7
  height: 27
  position:
  - 77
  - 62
  size:
  - 10
  - 10
  type: House
- block: 7
  height: 11
  position:
  - 77
  - 77
  size:
  - 10
  - 10
  type: Store
- block: 8
  height: 13
  position:
  - 62
  - 108
  size:
  - 10
  - 10
  type: Office
- block: 8
  height: 25
  position:
  - 62
  - 123
  size:
  - 10
  - 10
  type: Garage
- block: 8
  height: 23
  position:
  - 77
  - 108
  size:
  - 10
  - 10
  type: Office
- block: 8
  height: 17
  position:
  - 77
  - 123
  size:
  - 10
  - 10
  type: House
- block: 9
  height: 22
  position:
  - 62
  - 154
  size:
  - 10
  - 10
  type: Store
- block: 9
  height: 22
  position:
  - 62
  - 169
  size:
  - 10
  - 10
  type: Office
- block: 9
  height: 24
  position:
  - 77
  - 154
  size:
  - 10
  - 10
  type: House
- block: 9
  height: 16
  position:
  - 77
  - 169
  size:
  - 10
  - 10
  type: House
- block: 10
  height: 10
  position:
  - 62
  - 200
  size:
  - 10
  - 10
  type: Gas Station
- block: 10
  height: 20
  position:
  - 62
  - 215
  size:
  - 10
  - 10
  type: House
- block: 10
  height: 17
  position:
  - 77
  - 200
  size:
  - 10
  - 10
  type: House
- block: 10
  height: 10
  position:
  - 77
  - 215
  size:
  - 10
  - 10
  type: Store
- block: 11
  height: 19
  position:
  - 108
  - 16
  size:
  - 10
  - 10
  type: Store
- block: 11
  height: 18
  position:
  - 108
  - 31
  size:
  - 10
  - 10
  type: Office
- block: 11
  height: 18
  position:
  - 123
  - 16
  size:
  - 10
  - 10
  type: Store
- block: 11
  height: 11
  position:
  - 123
  - 31
  size:
  - 10
  - 10
  type: Store
- block: 12
  height: 14
  position:
  - 108
  - 62
  size:
  - 10
  - 10
  type: House
- block: 12
  height: 17
  position:
  - 108
  - 77
  size:
  - 10
  - 10
  type: Store
- block: 12
  height: 12
  position:
  - 123
  - 62
  size:
  - 10
  - 10
  type: Office
- block: 12
  height: 14
  position:
  - 123
  - 77
  size:
  - 10
  - 10
  type: Garage
- block: 13
  height: 12
  position:
  - 108
  - 108
  size:
  - 10
  - 10
  type: Store
- block: 13
  height: 23
  position:
  - 108
  - 123
  size:
  - 10
  - 10
  type: Store
- block: 13
  height: 18
  position:
  - 123
  - 108
  size:
  - 10
  - 10
  type: Garage
- block: 13
  height: 19
  position:
  - 123
  - 123
  size:
  - 10
  - 10
  type: Store
- block: 14
  height: 28
  position:
  - 108
  - 154
  size:
  - 10
  - 10
  type: Gas Station
- block: 14
  height: 16
  position:
  - 108
  - 169
  size:
  - 10
  - 10
  type: House
- block: 14
  height: 13
  position:
  - 123
  - 154
  size:
  - 10
  - 10
  type: Garage
- block: 14
  height: 16
  position:
  - 123
  - 169
  size:
  - 10
  - 10
  type: Store
- block: 15
  height: 20
  position:
  - 108
  - 200
  size:
  - 10
  - 10
  type: Gas Station
- block: 15
  height: 22
  position:
  - 108
  - 215
  size:
  - 10
  - 10
  type: Office
- block: 15
  height: 28
  position:
  - 123
  - 200
  size:
  - 10
  - 10
  type: House
- block: 15
  height: 11
  position:
  - 123
  - 215
  size:
  - 10
  - 10
  type: House
- block: 16
  height: 15
  position:
  - 154
  - 16
  size:
  - 10
  - 10
  type: Store
- block: 16
  height: 21
  position:
  - 154
  - 31
  size:
  - 10
  - 10
  type: Garage
- block: 16
  height: 20
  position:
  - 169
  - 16
  size:
  - 10
  - 10
  type: House
- block: 16
  height: 16
  position:
  - 169
  - 31
  size:
  - 10
  - 10
  type: Office
- block: 17
  height: 10
  position:
  - 154
  - 62
  size:
  - 10
  - 10
  type: Store
- block: 17
  height: 29
  position:
  - 154
  - 77
  size:
  - 10
  - 10
  type: Office
- block: 17
  height: 12
  position:
  - 169
  - 62
  size:
  - 10
  - 10
  type: Office
- block: 17
  height: 17
  position:
  - 169
  - 77
  size:
  - 10
  - 10
  type: House
- block: 18
  height: 14
  position:
  - 154
  - 108
  size:
  - 10
  - 10
  type: Garage
- block: 18
  height: 19
  position:
  - 154
  - 123
  size:
  - 10
  - 10
  type: Store
- block: 18
  height: 24
  position:
  - 169
  - 108
  size:
  - 10
  - 10
  type: Office
- block: 18
  height: 18
  position:
  - 169
  - 123
  size:
  - 10
  - 10
  type: House
- block: 19
  height: 26
  position:
  - 154
  - 154
  size:
  - 10
  - 10
  type: Gas Station
- block: 19
  height: 21
  position:
  - 154
  - 169
  size:
  - 10
  - 10
  type: Office
- block: 19
  height: 11
  position:
  - 169
  - 154
  size:
  - 10
  - 10
  type: Office
- block: 19
  height: 14
  position:
  - 169
  - 169
  size:
  - 10
  - 10
  type: Store
- block: 20
  height: 26
  position:
  - 154
  - 200
  size:
  - 10
  - 10
  type: Office
- block: 20
  height: 11
  position:
  - 154
  - 215
  size:
  - 10
  - 10
  type: Office
- block: 20
  height: 14
  position:
  - 169
  - 200
  size:
  - 10
  - 10
  type: Garage
- block: 20
  height: 10
  position:
  - 169
  - 215
  size:
  - 10
  - 10
  type: Office
- block: 21
  height: 11
  position:
  - 200
  - 16
  size:
  - 10
  - 10
  type: Office
- block: 21
  height: 15
  position:
  - 200
  - 31
  size:
  - 10
  - 10
  type: Garage
- block: 21
  height: 13
  position:
  - 215
  - 16
  size:
  - 10
  - 10
  type: Office
- block: 21
  height: 26
  position:
  - 215
  - 31
  size:
  - 10
  - 10
  type: House
- block: 22
  height: 14
  position:
  - 200
  - 62
  size:
  - 10
  - 10
  type: Store
- block: 22
  height: 15
  position:
  - 200
  - 77
  size:
  - 10
  - 10
  type: Store
- block: 22
  height: 25
  position:
  - 215
  - 62
  size:
  - 10
  - 10
  type: Office
- block: 22
  height: 18
  position:
  - 215
  - 77
  size:
  - 10
  - 10
  type: Store
- block: 23
  height: 15
  position:
  - 200
  - 108
  size:
  - 10
  - 10
  type: Office
- block: 23
  height: 12
  position:
  - 200
  - 123
  size:
  - 10
  - 10
  type: Store
- block: 23
  height: 13
  position:
  - 215
  - 108
  size:
  - 10
  - 10
  type: Garage
- block: 23
  height: 12
  position:
  - 215
  - 123
  size:
  - 10
  - 10
  type: House
- block: 24
  height: 29
  position:
  - 200
  - 154
  size:
  - 10
  - 10
  type: Store
- block: 24
  height: 29
  position:
  - 200
  - 169
  size:
  - 10
  - 10
  type: Store
- block: 24
  height: 17
  position:
  - 215
  - 154
  size:
  - 10
  - 10
  type: Store
- block: 24
  height: 27
  position:
  - 215
  - 169
  size:
  - 10
  - 10
  type: Office
- block: 25
  height: 20
  position:
  - 200
  - 200
  size:
  - 10
  - 10
  type: Store
- block: 25
  height: 27
  position:
  - 200
  - 215
  size:
  - 10
  - 10
  type: Office
- block: 25
  height: 19
  position:
  - 215
  - 200
  size:
  - 10
  - 10
  type: Store
- block: 25
  height: 25
  position:
  - 215
  - 215
  size:
  - 10
  - 10
  type: Office
grid_size:
- 250
- 250
streets:
- directions: 2
  length: 241
  orientation: vertical
  position:
  - 0
  - 0
  type: Traffic Street
  width: 11
- directions: 2
  length: 241
  orientation: horizontal
  position:
  - 0
  - 0
  type: Traffic Street
  width: 11
- directions: 2
  length: 241
  orientation: vertical
  position:
  - 0
  - 46
  type: Traffic Street
  width: 11
- directions: 2
  length: 241
  orientation: horizontal
  position:
  - 46
  - 0
  type: Traffic Street
  width: 11
- directions: 2
  length: 241
  orientation: vertical
  position:
  - 0
  - 92
  type: Traffic Street
  width: 11
- directions: 2
  length: 241
  orientation: horizontal
  position:
  - 92
  - 0
  type: Traffic Street
  width: 11
- directions: 2
  length: 241
  orientation: vertical
  position:
  - 0
  - 138
  type: Traffic Street
  width: 11
- directions: 2
  length: 241
  orientation: horizontal
  position:
  - 138
  - 0
  type: Traffic Street
  width: 11
- directions: 2
  length: 241
  orientation: vertical
  position:
  - 0
  - 184
  type: Traffic Street
  width: 11
- directions: 2
  length: 241
  orientation: horizontal
  position:
  - 184
  - 0
  type: Traffic Street
  width: 11
- directions: 2
  length: 241
  orientation: vertical
  position:
  - 0
  - 230
  type: Traffic Street
  width: 11
- directions: 2
  length: 241
  orientation: horizontal
  position:
  - 230
  - 0
  type: Traffic Street
  width: 11
- directions: 2
  length: 219
  orientation: vertical
  position:
  - 11
  - 11
  type: Walking Street
  width: 5
- directions: 2
  length: 219
  orientation: vertical
  position:
  - 11
  - 41
  type: Walking Street
  width: 5
- directions: 2
  length: 219
  orientation: horizontal
  position:
  - 11
  - 11
  type: Walking Street
  width: 5
- directions: 2
  length: 219
  orientation: horizontal
  position:
  - 41
  - 11
  type: Walking Street
  width: 5
- directions: 2
  length: 219
  orientation: vertical
  position:
  - 11
  - 57
  type: Walking Street
  width: 5
- directions: 2
  length: 219
  orientation: vertical
  position:
  - 11
  - 87
  type: Walking Street
  width: 5
- directions: 2
  length: 219
  orientation: horizontal
  position:
  - 57
  - 11
  type: Walking Street
  width: 5
- directions: 2
  length: 219
  orientation: horizontal
  position:
  - 87
  - 11
  type: Walking Street
  width: 5
- directions: 2
  length: 219
  orientation: vertical
  position:
  - 11
  - 103
  type: Walking Street
  width: 5
- directions: 2
  length: 219
  orientation: vertical
  position:
  - 11
  - 133
  type: Walking Street
  width: 5
- directions: 2
  length: 219
  orientation: horizontal
  position:
  - 103
  - 11
  type: Walking Street
  width: 5
- directions: 2
  length: 219
  orientation: horizontal
  position:
  - 133
  - 11
  type: Walking Street
  width: 5
- directions: 2
  length: 219
  orientation: vertical
  position:
  - 11
  - 149
  type: Walking Street
  width: 5
- directions: 2
  length: 219
  orientation: vertical
  position:
  - 11
  - 179
  type: Walking Street
  width: 5
- directions: 2
  length: 219
  orientation: horizontal
  position:
  - 149
  - 11
  type: Walking Street
  width: 5
- directions: 2
  length: 219
  orientation: horizontal
  position:
  - 179
  - 11
  type: Walking Street
  width: 5
- directions: 2
  length: 219
  orientation: vertical
  position:
  - 11
  - 195
  type: Walking Street
  width: 5
- directions: 2
  length: 219
  orientation: vertical
  position:
  - 11
  - 225
  type: Walking Street
  width: 5
- directions: 2
  length: 219
  orientation: horizontal
  position:
  - 195
  - 11
  type: Walking Street
  width: 5
- directions: 2
  length: 219
  orientation: horizontal
  position:
  - 225
  - 11
  type: Walking Street
  width: 5
- directions: 2
  length: 25
  orientation: vertical
  position:
  - 16
  - 26
  type: Walking Street
  width: 5
- directions: 2
  length: 25
  orientation: horizontal
  position:
  - 26
  - 16
  type: Walking Street
  width: 5
- directions: 2
  length: 25
  orientation: vertical
  position:
  - 16
  - 72
  type: Walking Street
  width: 5
- directions: 2
  length: 25
  orientation: horizontal
  position:
  - 26
  - 62
  type: Walking Street
  width: 5
- directions: 2
  length: 25
  orientation: vertical
  position:
  - 16
  - 118
  type: Walking Street
  width: 5
- directions: 2
  length: 25
  orientation: horizontal
  position:
  - 26
  - 108
  type: Walking Street
  width: 5
- directions: 2
  length: 25
  orientation: vertical
  position:
  - 16
  - 164
  type: Walking Street
  width: 5
- directions: 2
  length: 25
  orientation: horizontal
  position:
  - 26
  - 154
  type: Walking Street
  width: 5
- directions: 2
  length: 25
  orientation: vertical
  position:
  - 16
  - 210
  type: Walking Street
  width: 5
- directions: 2
  length: 25
  orientation: horizontal
  position:
  - 26
  - 200
  type: Walking Street
  width: 5
- directions: 2
  length: 25
  orientation: vertical
  position:
  - 62
  - 26
  type: Walking Street
  width: 5
- directions: 2
  length: 25
  orientation: horizontal
  position:
  - 72
  - 16
  type: Walking Street
  width: 5
- directions: 2
  length: 25
  orientation: vertical
  position:
  - 62
  - 72
  type: Walking Street
  width: 5
- directions: 2
  length: 25
  orientation: horizontal
  position:
  - 72
  - 62
  type: Walking Street
  width: 5
- directions: 2
  length: 25
  orientation: vertical
  position:
  - 62
  - 118
  type: Walking Street
  width: 5
- directions: 2
  length: 25
  orientation: horizontal
  position:
  - 72
  - 108
  type: Walking Street
  width: 5
- directions: 2
  length: 25
  orientation: vertical
  position:
  - 62
  - 164
  type: Walking Street
  width: 5
- directions: 2
  length: 25
  orientation: horizontal
  position:
  - 72
  - 154
  type: Walking Street
  width: 5
- directions: 2
  length: 25
  orientation: vertical
  position:
  - 62
  - 210
  type: Walking Street
  width: 5
- directions: 2
  length: 25
  orientation: horizontal
  position:
  - 72
  - 200
  type: Walking Street
  width: 5
- directions: 2
  length: 25
  orientation: vertical
  position:
  - 108
  - 26
  type: Walking Street
  width: 5
- directions: 2
  length: 25
  orientation: horizontal
  position:
  - 118
  - 16
  type: Walking Street
  width: 5
- directions: 2
  length: 25
  orientation: vertical
  position:
  - 108
  - 72
  type: Walking Street
  width: 5
- directions: 2
  length: 25
  orientation: horizontal
  position:
  - 118
  - 62
  type: Walking Street
  width: 5
- directions: 2
  length: 25
  orientation: vertical
  position:
  - 108
  - 118
  type: Walking Street
  width: 5
- directions: 2
  length: 25
  orientation: horizontal
  position:
  - 118
  - 108
  type: Walking Street
  width: 5
- directions: 2
  length: 25
  orientation: vertical
  position:
  - 108
  - 164
  type: Walking Street
  width: 5
- directions: 2
  length: 25
  orientation: horizontal
  position:
  - 118
  - 154
  type: Walking Street
  width: 5
- directions: 2
  length: 25
  orientation: vertical
  position:
  - 108
  - 210
  type: Walking Street
  width: 5
- directions: 2
  length: 25
  orientation: horizontal
  position:
  - 118
  - 200
  type: Walking Street
  width: 5
- directions: 2
  length: 25
  orientation: vertical
  position:
  - 154
  - 26
  type: Walking Street
  width: 5
- directions: 2
  length: 25
  orientation: horizontal
  position:
  - 164
  - 16
  type: Walking Street
  width: 5
- directions: 2
  length: 25
  orientation: vertical
  position:
  - 154
  - 72
  type: Walking Street
  width: 5
- directions: 2
  length: 25
  orientation: horizontal
  position:
  - 164
  - 62
  type: Walking Street
  width: 5
- directions: 2
  length: 25
  orientation: vertical
  position:
  - 154
  - 118
  type: Walking Street
  width: 5
- directions: 2
  length: 25
  orientation: horizontal
  position:
  - 164
  - 108
  type: Walking Street
  width: 5
- directions: 2
  length: 25
  orientation: vertical
  position:
  - 154
  - 164
  type: Walking Street
  width: 5
- directions: 2
  length: 25
  orientation: horizontal
  position:
  - 164
  - 154
  type: Walking Street
  width: 5
- directions: 2
  length: 25
  orientation: vertical
  position:
  - 154
  - 210
  type: Walking Street
  width: 5
- directions: 2
  length: 25
  orientation: horizontal
  position:
  - 164
  - 200
  type: Walking Street
  width: 5
- directions: 2
  length: 25
  orientation: vertical
  position:
  - 200
  - 26
  type: Walking Street
  width: 5
- directions: 2
  length: 25
  orientation: horizontal
  position:
  - 210
  - 16
  type: Walking Street
  width: 5
- directions: 2
  length: 25
  orientation: vertical
  position:
  - 200
  - 72
  type: Walking Street
  width: 5
- directions: 2
  length: 25
  orientation: horizontal
  position:
  - 210
  - 62
  type: Walking Street
  width: 5
- directions: 2
  length: 25
  orientation: vertical
  position:
  - 200
  - 118
  type: Walking Street
  width: 5
- directions: 2
  length: 25
  orientation: horizontal
  position:
  - 210
  - 108
  type: Walking Street
  width: 5
- directions: 2
  length: 25
  orientation: vertical
  position:
  - 200
  - 164
  type: Walking Street
  width: 5
- directions: 2
  length: 25
  orientation: horizontal
  position:
  - 210
  - 154
  type: Walking Street
  width: 5
- directions: 2
  length: 25
  orientation: vertical
  position:
  - 200
  - 210
  type: Walking Street
  width: 5
- directions: 2
  length: 25
  orientation: horizontal
  position:
  - 210
  - 200
  type: Walking Street
  width: 5
