grid_size: [250, 250]

streets:
  # Main horizontal traffic streets
  - position: [0, 0]
    length: 250
    orientation: 'horizontal'
    type: 'Traffic Street'
    directions: 2
    width: 7

  - position: [243, 0]
    length: 250
    orientation: 'horizontal'
    type: 'Traffic Street'
    directions: 2
    width: 7
  
  - position: [7, 7]
    length: 236
    orientation: 'horizontal'
    type: 'Walking Street'
    directions: 2
    width: 3

  - position: [240, 7]
    length: 236
    orientation: 'horizontal'
    type: 'Walking Street'
    directions: 2
    width: 3

  # Main vertical traffic streets
  - position: [0, 0]
    length: 250
    orientation: 'vertical'
    type: 'Traffic Street'
    directions: 2
    width: 7
  
  - position: [0, 243]
    length: 250
    orientation: 'vertical'
    type: 'Traffic Street'
    directions: 2
    width: 7

  - position: [7, 7]
    length: 236
    orientation: 'vertical'
    type: 'Walking Street'
    directions: 2
    width: 3

  - position: [7, 240]
    length: 236
    orientation: 'vertical'
    type: 'Walking Street'
    directions: 2
    width: 3

agents:
  - type: 'Pedestrian'
    id: 1
    size: 1
    gplanner: 'A*'

  - type: 'Pedestrian'
    id: 2
    size: 1
    gplanner: 'A*'

  - type: 'Pedestrian'
    id: 3
    size: 1
    gplanner: 'A*'

  - type: 'Car'
    id: 1
    size: 2
    gplanner: 'A*'

  - type: 'Car'
    id: 2
    size: 2
    gplanner: 'A*'