# class defines the "python class" for the agent, affecting global planning, concepts define local decision rules, make sure the first is the RL agent
agents:
- class: Private_car
  id: 1
  size: 2
  gplanner: A*vg
  concepts:
    type: Car
    priority: 1

- class: Pedestrian
  id: 1
  size: 1
  gplanner: A*
  concepts:
    type: Pedestrian
    priority: 0
    old: 1.0

- class: Private_car
  id: 6
  size: 2
  gplanner: A*vg
  concepts:
    type: Car
    ambulance: 1.0
    priority: 6