# class defines the "python class" for the agent, affecting global planning, concepts define local decision rules
agents:
- class: Pedestrian
  id: 1
  size: 1
  gplanner: A*
  concepts:
    type: Pedestrian
    old: 1.0

- class: Pedestrian
  id: 2
  size: 1
  gplanner: A*
  concepts:
    type: Pedestrian

- class: Pedestrian
  id: 3
  size: 1
  gplanner: A*
  concepts:
    type: Pedestrian

- class: Pedestrian
  id: 4
  size: 1
  lplanner: LNN
  gplanner: A*
  concepts:
    type: Pedestrian
    young: 1.0

- class: Pedestrian
  id: 5
  size: 1
  gplanner: A*
  concepts:
    type: Pedestrian

- class: Pedestrian
  id: 6
  size: 1
  gplanner: A*
  concepts:
    type: Pedestrian
    old: 1.0

- class: Pedestrian
  id: 7
  size: 1
  lplanner: LNN
  gplanner: A*
  concepts:
    type: Pedestrian

- class: Pedestrian
  id: 8
  size: 1
  gplanner: A*
  concepts:
    type: Pedestrian
    old: 1.0

- class: Pedestrian
  id: 9
  size: 1
  gplanner: A*
  concepts:
    type: Pedestrian

- class: Pedestrian
  id: 10
  size: 1
  lplanner: LNN
  gplanner: A*
  concepts:
    type: Pedestrian

- class: Pedestrian
  id: 11
  size: 1
  gplanner: A*
  concepts:
    type: Pedestrian
    young: 1.0

- class: Pedestrian
  id: 12
  size: 1
  gplanner: A*
  concepts:
    type: Pedestrian

- class: Pedestrian
  id: 13
  size: 1
  gplanner: A*
  concepts:
    type: Pedestrian

- class: Pedestrian
  id: 14
  size: 1
  gplanner: A*
  concepts:
    type: Pedestrian
    old: 1.0

- class: Pedestrian
  id: 15
  size: 1
  gplanner: A*
  concepts:
    type: Pedestrian
    

- class: Pedestrian
  id: 16
  size: 1
  gplanner: A*
  concepts:
    type: Pedestrian

- class: Pedestrian
  id: 17
  size: 1
  gplanner: A*
  concepts:
    type: Pedestrian

- class: Pedestrian
  id: 18
  size: 1
  gplanner: A*
  concepts:
    type: Pedestrian

- class: Pedestrian
  id: 19
  size: 1
  gplanner: A*
  concepts:
    type: Pedestrian

- class: Pedestrian
  id: 20
  size: 1
  gplanner: A*
  concepts:
    type: Pedestrian
    old: 1.0

- class: Pedestrian
  id: 21
  size: 1
  gplanner: A*
  concepts:
    type: Pedestrian

- class: Pedestrian
  id: 22
  size: 1
  gplanner: A*
  concepts:
    type: Pedestrian

- class: Pedestrian
  id: 23
  size: 1
  gplanner: A*
  concepts:
    type: Pedestrian

- class: Pedestrian
  id: 24
  size: 1
  gplanner: A*
  concepts:
    type: Pedestrian
    old: 1.0

- class: Pedestrian
  id: 25
  size: 1
  gplanner: A*
  concepts:
    type: Pedestrian

- class: Pedestrian
  id: 26
  size: 1
  gplanner: A*
  concepts:
    type: Pedestrian

- class: Pedestrian
  id: 27
  size: 1
  gplanner: A*
  concepts:
    type: Pedestrian

- class: Pedestrian
  id: 28
  size: 1
  gplanner: A*
  concepts:
    type: Pedestrian

- class: Pedestrian
  id: 29
  size: 1
  gplanner: A*
  concepts:
    type: Pedestrian

- class: Pedestrian
  id: 30
  size: 1
  gplanner: A*
  concepts:
    type: Pedestrian

- class: Private_car
  id: 1
  size: 2
  gplanner: A*vg
  concepts:
    type: Car
    ambulance: 1.0

- class: Private_car
  id: 2
  size: 2
  gplanner: A*vg
  concepts:
    type: Car
    ambulance: 1.0

- class: Private_car
  id: 3
  size: 2
  gplanner: A*vg
  concepts:
    type: Car

- class: Private_car
  id: 4
  size: 2
  gplanner: A*vg
  concepts:
    type: Car
    tiro: 1.0

- class: Bus
  id: 5
  size: 2
  gplanner: A*vg
  concepts:
    type: Car
    bus: 1.0
    no.: 61A # no. is used to define the bus routes 

- class: Private_car
  id: 6
  size: 2
  gplanner: A*vg
  concepts:
    type: Car
    tiro: 1.0

- class: Private_car
  id: 7
  size: 2
  gplanner: A*vg
  concepts:
    type: Car
    tiro: 1.0

- class: Private_car
  id: 8
  size: 2
  gplanner: A*vg
  concepts:
    type: Car
    reckless: 1.0

- class: Private_car
  id: 9
  size: 2
  gplanner: A*vg
  concepts:
    type: Car
    police: 1.0

- class: Private_car
  id: 10
  size: 2
  gplanner: A*vg
  concepts:
    type: Car

- class: Private_car
  id: 11
  size: 2
  gplanner: A*vg
  concepts:
    type: Car

- class: Private_car
  id: 12
  size: 2
  gplanner: A*vg
  concepts:
    type: Car
