# class defines the "python class" for the agent, affecting global planning, concepts define local decision rules
agents:
- class: Pedestrian
  id: 1
  size: 1
  gplanner: A*
  concepts:
    type: Pedestrian
    mayor: 1.0
