# class defines the "python class" for the agent, affecting global planning, concepts define local decision rules
agents:
- class: Pedestrian
  id: 1
  size: 1
  gplanner: A*
  concepts:
    type: Pedestrian
    old: 1.0

- class: Pedestrian
  id: 2
  size: 1
  gplanner: A*
  concepts:
    type: Pedestrian

- class: Pedestrian
  id: 3
  size: 1
  gplanner: A*
  concepts:
    type: Pedestrian

- class: Pedestrian
  id: 4
  size: 1
  lplanner: LNN
  gplanner: A*
  concepts:
    type: Pedestrian

- class: Private_car
  id: 1
  size: 1
  gplanner: A*vg
  concepts:
    type: Car
    ambulance: 1.0

- class: Private_car
  id: 2
  size: 1
  gplanner: A*vg
  concepts:
    type: Car
    ambulance: 1.0

- class: Private_car
  id: 3
  size: 1
  gplanner: A*vg
  concepts:
    type: Car

- class: Private_car
  id: 4
  size: 1
  gplanner: A*vg
  concepts:
    type: Car
    tiro: 1.0

- class: Bus
  id: 5
  size: 1
  gplanner: A*vg
  concepts:
    type: Car
    bus: 1.0
    no.: 61A # no. is used to define the bus routes 