# class defines the "python class" for the agent, affecting global planning, concepts define local decision rules
agents:
- class: Pedestrian
  id: 1
  size: 1
  gplanner: A*
  concepts:
    type: Pedestrian
    mayor: 1.0

- class: Pedestrian
  id: 2
  size: 1
  gplanner: A*
  concepts:
    type: Pedestrian
    mayor: 1.0

- class: Pedestrian
  id: 3
  size: 1
  gplanner: A*
  concepts:
    type: Pedestrian
    mayor: 1.0

- class: Pedestrian
  id: 4
  size: 1
  lplanner: LNN
  gplanner: A*
  concepts:
    type: Pedestrian
    mayor: 1.0

# - type: Pedestrian
#   id: 5
#   size: 1
#   gplanner: A*

# - type: Pedestrian
#   id: 6
#   size: 1
#   gplanner: A*

# - type: Pedestrian
#   id: 7
#   size: 1
#   gplanner: A*

# - type: Pedestrian
#   id: 8
#   size: 1
#   gplanner: A*

# - type: Pedestrian
#   id: 9
#   size: 1
#   lplanner: LNN
#   gplanner: A*

# - type: Pedestrian
#   id: 10
#   size: 1
#   gplanner: A*

# - type: Pedestrian
#   id: 11
#   size: 1
#   gplanner: A*

# - type: Pedestrian
#   id: 12
#   size: 1
#   gplanner: A*

# - type: Pedestrian
#   id: 13
#   size: 1
#   gplanner: A*

# - type: Pedestrian
#   id: 14
#   size: 1
#   lplanner: LNN
#   gplanner: A*

# - type: Pedestrian
#   id: 15
#   size: 1
#   gplanner: A*

# - type: Pedestrian
#   id: 16
#   size: 1
#   gplanner: A*

# - type: Pedestrian
#   id: 17
#   size: 1
#   gplanner: A*
# - type: Pedestrian
#   id: 8
#   size: 1
#   gplanner: A*

# - type: Pedestrian
#   id: 18
#   size: 1
#   lplanner: LNN
#   gplanner: A*

# - type: Pedestrian
#   id: 19
#   size: 1
#   gplanner: A*

# - type: Pedestrian
#   id: 20
#   size: 1
#   gplanner: A*

- class: Private_car
  id: 1
  size: 1
  gplanner: A*vg
  concepts:
    type: Car
    ambulance: 1.0

- class: Private_car
  id: 2
  size: 1
  gplanner: A*vg
  concepts:
    type: Car
    ambulance: 0.0

- class: Private_car
  id: 3
  size: 1
  gplanner: A*vg
  concepts:
    type: Car
    ambulance: 0.0

- class: Private_car
  id: 4
  size: 1
  gplanner: A*vg
  concepts:
    type: Car
    ambulance: 0.0

# - class: Bus
#   id: 5
#   size: 1
#   gplanner: A*vg
#   concepts:
#     type: Car
#     ambulance: 0.0
# - type: Car
#   id: 5
#   size: 1
#   gplanner: A*vg

# - type: Car
#   id: 6
#   size: 1
#   gplanner: A*vg

# - type: Car
#   id: 7
#   size: 1
#   gplanner: A*vg

# - type: Car
#   id: 8
#   size: 1
#   gplanner: A*vg

# - type: Car
#   id: 9
#   size: 1
#   gplanner: A*vg

# - type: Car
#   id: 10
#   size: 1
#   gplanner: A*vg

# - type: Car
#   id: 11
#   size: 1
#   gplanner: A*vg

# - type: Car
#   id: 12
#   size: 1
#   gplanner: A*vg
