# General simulation settings
simulation:
  map_yaml_file: "config/maps/square_5x5.yaml"       # OpenAI Gym environment name
  agent_yaml_file: "config/agents/easy/test.yaml" # Agents in the simulation
  ontology_yaml_file: "config/rules/ontology.yaml" # Ontology of the simulation
  rule_type: "Z3_RL"               # z3 rl will set the rl_agent with fixed number of other entities, return the groundings as obs, and return the rule reward
  rule_yaml_file: "config/rules/Nav/easy/rl.yaml"                    # Whether to render the environment
  rl: true
  debug: false
  use_multi: false
  agent_region: 140
  rl_agent: 
    max_priority: 7
    use_expert: false
    agent_name: "Car_1"               # ID of the RL agent, this is the agent id in the agent yaml file
    max_horizon: 500                          # Maximum steps in each episode 
    action_space: 4                       # Number of discrete actions, 4 means slow/normal/fast/stop
    action_mapping:                       # Mapping from policy action index to actual action space, see /agent folder
      0: [1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0]
      1: [0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0]
      2: [0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0]
      3: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]
    fov_entities:
      Entity: 5                        # Maximum number of entities in the FOV, include the RL agent
    action_cost:
      0: -2
      1: -1
      2: 0
      3: -3

# Stable Baselines specific settings
stable_baselines:
  algorithm: "HRI"
  policy_network: "HriPolicy"
  policy_kwargs:
    Stop:
      num_background: 14 
      num_features: 34
      max_depth: 3
      tgt_arity: 1
      predicates_labels: ['CollidingClose', 'Fast', 'HigherPri', 'IsAmbulance', 'IsAtInter', 'IsCar', 'IsClose', 'IsInInter', 'IsOld', 'IsPedestrian', 'IsTiro', 'Stop', 'ident', 'sees']
  hyperparameters:
    tgt_action: ['Stop']
    default_action: 'Fast'
    threshold: 0.5
    action2idx: {'Slow': 0, 'Normal': 1, 'Fast': 2, 'Stop': 3}
    pred2ind: 
      Stop: {'CollidingClose': 0, 'Fast': 1, 'HigherPri': 2, 'IsAmbulance': 3, 'IsAtInter': 4, 'IsCar': 5, 'IsClose': 6, 'IsInInter': 7, 'IsOld': 8, 'IsPedestrian': 9, 'IsTiro': 10, 'Stop': 11, 'ident': 12, 'sees': 13}
    if_un_pred: 
      Stop: [False, True, False, True, True, True, False, True, True, True, True, True, False, False]
  train: false                   # Whether to train the model
  checkpoint_path: "checkpoints/final_models/easy/hri"           # Path to a checkpoint to restore the model from
  num_envs: 1                   # Number of environments to run in parallel
  episode_data: "dataset/easy/test_100_episodes.pkl"
